# Generated by Django 5.0.4 on 2024-09-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="phone",
        ),
    ]
