# Generated by Django 5.0.4 on 2024-04-26 06:45

import profile.models

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="profile",
        ),
        migrations.DeleteModel(
            name="Lifestyle",
        ),
        migrations.AddField(
            model_name="profile",
            name="drinking_frequency",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=profile.models.profile_image_file_path
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_smoke",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="religion",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="account.question",
            ),
        ),
        migrations.AlterField(
            model_name="answerhistory",
            name="answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="account.answer",
            ),
        ),
        migrations.AlterField(
            model_name="answerhistory",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="account.profile",
            ),
        ),
        migrations.AlterField(
            model_name="answerhistory",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="histories",
                to="account.question",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
