# Generated by Django 5.0.4 on 2024-11-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0003_alter_profile_options_profile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="category",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
