# Generated by Django 5.0.4 on 2024-05-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_rename_question_simulation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("daily", "DAILY"), ("mbti", "MBTI"), ("food", "FOOD")],
                max_length=20,
            ),
        ),
    ]
