# Generated by Django 5.0.4 on 2024-07-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_answerchoice_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="drinking_frequency",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("남성", "male"), ("여성", "female")],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="job",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="religion",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
