version: "3.9"

services:
  app:
    image: melbong/banada_be
    expose:
      - "${APP_PORT}"
    restart: always
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py test &&
      gunicorn config.wsgi:application --bind 0.0.0.0:${APP_PORT}
      "
    depends_on:
      - banada-db
    env_file:
      - .env

  banada-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    env_file:
      - .env
    volumes:
      - banada-db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "8000:${LISTEN_PORT}"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env
    depends_on:
      - app

volumes:
  banada-db-data:
