version: "3.9"

services:
  app:
    image: melbong/banada_be
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate
            "
    env_file:
      - .env

  banada-db:
    image: postgres:16-alpine
    volumes:
      - banada-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    env_file:
      - .env

volumes:
  banada-db-data:
