version: "3.9"

services:
  app:
    env_file:
      - .env
    expose:
      - "${APP_PORT}"
    restart: always
    depends_on:
      - banada-db

  banada-db:
    image: postgres:16-alpine
    env_file:
      - .env
    command: >
      sh -c "python manage.py test &&
      gunicorn config.wsgi:application --bind 0.0.0.0:${APP_PORT}
      "
    volumes:
      - banada-db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "8000:${LISTEN_PORT}"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env
    depends_on:
      - app

volumes:
  banada-db-data:
