# Generated by Django 5.0.4 on 2024-05-08 08:11

import contact.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[("승낙", "ACCEPT"), ("대기중", "WAIT"), ("거절", "REFUSE")],
                default=contact.enums.MessageStatus["WAIT"],
                max_length=20,
            ),
        ),
    ]
