# Generated by Django 5.0.4 on 2024-05-15 10:57

import contact.enums
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_simulation_category"),
        ("contact", "0002_alter_message_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("message", "MESSAGE"),
                            ("ring", "RING"),
                            ("heart", "HEART"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cost", models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="account.profile",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("accept", "ACCEPT"),
                    ("pending", "WAIT"),
                    ("refuse", "REFUSE"),
                ],
                default=contact.enums.MessageStatus["WAIT"],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contact.messagetype",
            ),
        ),
    ]
