# Generated by Django 5.0.4 on 2024-07-04 00:30

import contact.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_contact_created_time_contact_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "ACCEPTED"),
                    ("pending", "WAIT"),
                    ("refused", "REFUSED"),
                    ("expired", "EXPIRED"),
                ],
                default=contact.enums.MessageStatus["WAIT"],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="messagetype",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[("message", "MESSAGE"), ("ring", "RING"), ("heart", "HEART")],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="snsinfo",
            name="service",
            field=models.CharField(
                blank=True,
                choices=[("kakao", "KAKAO"), ("instagram", "INSTA")],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="snsinfo",
            name="username",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
