# Generated by Django 5.0.4 on 2024-04-27 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_image_profileimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Simulation',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='simulation',
        ),
        migrations.AddField(
            model_name='answer',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='account.profile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnswerHistory',
        ),
    ]
