# Generated by Django 5.0.4 on 2024-06-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_profile_age_profile_created_time_profile_gender_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="answerchoice",
            constraint=models.UniqueConstraint(
                fields=("simulation", "index"), name="unique_simulation_index"
            ),
        ),
    ]
