# Generated by Django 5.0.4 on 2024-06-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_answerchoice_unique_simulation_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerchoice",
            name="index",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
