# Generated by Django 5.0.4 on 2024-07-04 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_alter_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="유효한 전화번호 형식이 아닙니다: 010-1234-5678 혹은 +82-10-1234-5678",
                        regex="^(\\+82|0)?1[0-9]{1}-?[0-9]{3,4}-?[0-9]{4}$",
                    )
                ],
            ),
        ),
    ]
