name: Banada

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/banada_be
          TAG=${{ github.ref == 'refs/heads/main' && echo 'latest' || echo 'dev' }}

          docker buildx build --push --tag $IMAGE_NAME:$TAG .

  deploy-development:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    needs: build-and-push-docker-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull and run Docker containers for development
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/banada_be
          TAG=dev

          docker pull $IMAGE_NAME:$TAG
          docker-compose --env-
